---
bibliography: references.bib
format: pdf
---

# Studie design

I denne oppgaven skal jeg diskutere hvordan fem forskjellige studier har gått frem for å besvare sine problemstillinger. Studiene jeg har sett på ønsker å finne ut hvordan en HIT-blokk (høy-intensiv intervall trening) påvirker utholdenhetsprestasjon for trente idrettsutøvere. De ønsker med andre ord å optimalisere utholdenhetstrening ved å organisere hardøktene på en bedre måte. Studiene blokkperiodiserer hovedsakelig HIT og sammenligner det mot tradisjonell periodisering, der en fordeler hardøktene jevnt utover uken.

I nyere tid er det blitt populært å organisere trening i bolker, såkalt blokkperiodisering. I en bolk kan man fokusere på noen få bestemte fysiologiske faktorer, samtidig som de andre faktorene vedlikeholdes. En slik tilnærming ble brukt av toppidrettstrenere allerede på 1980-tallet [@issurin2010]. Når man når et høyt fysiologisk nivå, vil det kreve et langt større treningsstimuli for å oppnå progresjon i prestasjonsnivået. Dette er noe som samtlige studier legger frem. Bent Rønnestad sin artikkel fra 2014 [@rønnestad2014] legger også frem at det ikke er noen godt gjennomførte studier som ser på samorganiseringen mellom LIT (lav-intensiv intervall trening) og HIT trening for å øke prestasjonsnivået. Studienes hypotese er at blokkperiodisering vil føre til større forbedring i sykkelprestasjon versus tradisjonell periodisering. Rønnestad sine artikler har svært varierende hypoteser, selv om studiene er organisert på lik måte. Det kan tenkes at hypotesen er satt opp etter at dataene er samlet inn, da de overraskende nok alltid stemmer overens med resultatene [@rønnestad2019; @rønnestad2014; @rønnestad2016; @rønnestad]. Denne tilnærmingen kan føre til mangel på en forhåndsbestemt metode for de statistiske analysene. Dette kan komplisere tolkningen av resultatene og gjøre det vanskelig å vurdere påliteligheten av studien. Dette kan også føre til redusert troverdighet hos forskeren.

En årsak som kan føre til at deres hypotese stemmer kan være at bolkgruppene vil få en større mekanisk belastning over en kortere tidsperiode som er et sentralt signal til tilpasning. I teorien kan høyere intensitet også gi en større aktivering av viktige signaler som f.eks. \[AMP\], \[ADP\], \[NO & ROS\] og \[Ca2+\] [@tønnesen2018].

[@rønnestad2016; @rønnestad2019; @almquist2022] var randomiserte kontrollerte studier. Det vil si at deltagerne ble tilfeldig plassert i en av gruppene. Randomisering i kliniske studier er avgjørende for å sikre objektivitet. Deltakere bør kvalifisere seg og gi samtykke for randomisering [@hulley2013]. [@rønnestad2014; @rønnestad] var ikke-randomiserte kontrollerte studier. Det er en svakhet i studiene til Rønnestad fra 2014 at de ikke er randomiserte. Randomiserte studier er mer effektive enn ikke-randomiserte studier fordi det utelukker påvirkningen av andre variabler [@hulley2013]. Det vil altså føre til at resultatene i studiene blir mindre pålitelige. Ved å tilfeldig fordele forsøkspersoner til bestemte grupper eliminerer man systematiske forskjeller mellom gruppene. Dette reduserer risikoen for skjevhet i fordelingen og sørger for at eventuelle forskjeller i resultatet mellom gruppene trolig skyldes den intervensjonen som er gjennomført.

Samtlige studier hadde et kontrollert studiedesign. Et kontrollert studiedesign, også kjent som en kontrollert klinisk studie, er en type studiedesign der forskere aktivt kontrollerer og manipulerer variabler for å undersøke effekten av en intervensjon. Her er det også vanlig å ha en egen kontrollgruppe, slik vi har sett i disse studiene. Kontrollgruppen gir et referansepunkt for å sammenligne resultatene mellom gruppene. Ved å sammenligne resultatene mellom de som mottar behandlingen (intervensjonsgruppen) og de som ikke gjør det (kontrollgruppen), kan forskere vurdere om de observerte endringene er en reell effekt av behandlingen eller om de kan skyldes andre faktorer. Dette kan for eksempel bidra med å utelukke en eventuell læringseffekt man vil få av å gjennomføre testingen underveis i et prosjekt. Hvis man ikke har med en kontrollgruppe vil denne læringseffekten bidra med å få resultatene til å evaluere mer enn kun intervensjonen som er gjennomført.

Majoriteten av studiene har med seg alt fra trente til eliteutøvere, det er variasjon mellom studiene i hvor godt trente forsøkspersonene var basert på klassifiseringen til De Pauw (2013) og Jeukendrup (2000). [@pauw2013; @jeukendrup2000]. Dette utvalget av forsøkspersoner definerer ikke populasjonen som helhet, men de har et utvalg som er spesifikt for deres problemstilling. I studiene til Bent Rønnestad [@rønnestad2014; @rønnestad2016; @rønnestad2019; @rønnestad] er det ikke spesifisert hvor forsøkspersonene ble rekruttert. I studien til [@almquist2022] legger de frem at forsøkspersonene ble rekruttert fra lokale sykkelklubber som lå i nær tilknytning til de forskjellige testlokalene. Fremgangsmåten man velger for å rekruttere forsøkspersoner kan føre til generalisering. Hvis man får forsøkspersoner til å melde seg på selv, vil man ofte ende opp med personer som er svært motiverte til å trene. Hvis man utlyser en søknad via sosiale medier vil det øke sannsynligheten for at den gjennomsnittlige alderen vil være lavere. Det er derfor viktig at man nøye vurderer hvilken fremgangsmåte man tar for å rekruttere forsøkspersoner basert på utvalget studien ønsker.

Samtlige studier startet med en pre-test der forsøkspersonene gjennomfører sykkeltester. Til felles for alle studiene gjennomførte forsøkspersonene en VO2maks-test. Samtlige studier utenom [@rønnestad2019] gjennomførte laktatprofil [@rønnestad2019]. [@almquist2022; @rønnestad2014] gjennomførte også en 40 minutter all-out-test og måling av HB-masse. [@rønnestad2019] gjennomførte også flere styrketester.

Etter pre-testene gjennomføre forsøkspersonene en lengre treningsintervensjon. De ble i alle studiene fordelt inn i to grupper, der en gruppe trente med tradisjonell periodisering og den andre trente med blokkperiodisering. Varigheten på intervensjonen og den spesifikke fordelingen av hardøkter varierte mellom gruppene. [@rønnestad2014] hadde en treningsperiode på 4 uker. Blokkgruppen gjennomførte 5 HIT økter i uke 1, og 1 HIT økt de 3 resterende ukene. Den tradisjonelle gruppen gjennomførte 2 HIT økter ukentlig. Både [@almquist2022; @rønnestad] gjennomførte en 12-ukers treningsintervensjon. Forskjellen mellom disse to studiene var at [@almquist2022] varierte mellom HIT, MIT (moderat intensiv trening) og LIT på bolkgruppen. [@rønnestad2014] Hadde kun en uke med HIT trening (5x HIT) før de hadde 3 uker med fokus på LIT (1x HIT i disse ukene). Begge gruppene hadde mesosykluser på 4 uker som de repeterte 3 ganger. [@rønnestad2014] gjennomførte en treningsintervensjon på 5 uker med følgende mengde HIT økter: 5 + 1 + 3 + 1 + 1. Den tradisjonelle periodiseringen gjennomførte 2 + 2 + 3 + 2 + 2 [@rønnestad2016]. [@rønnestad2019] gjennomførte en intervensjon på 6 uker. I tillegg til periodisering av HIT trening gjennomførte de også periodisering av styrketrening. Bolkgruppen gjennomførte 1 + 5 + 1 + 1 + 5 + 1 HIT-økter og den tradisjonelle gruppen gjennomførte 2 + 3 + 2 + 2 + 3 + 2 [@rønnestad2019]. Samtlige studier hadde lik totalbelastning mellom de to intervensjonsgruppene.

Studiene presenterer data ved å gi gjennomsnittsverdier og tilhørende standardavvik. Dette gir en konsistent måte å rapportere resultatene på og gjør det enkelt for leseren å forstå variasjonen i dataene. Når det gjelder vurdering av effektstørrelser bruker [@rønnestad2014] Cohen's d med en klassifisering av effektstørrelser som trivial, liten, moderat, stor eller svært stor, mens [@rønnestad] brukte korrelasjonskoeffisienter (r) med samme klassifiseringer.

Når de testet for statistiske forskjeller mellom de to gruppene, benytter alle artiklene t-tester. Imidlertid er det variasjon i hvilke t-tester som brukes. For eksempel bruker [@rønnestad2014] både uparede og parede t-tester for å sammenligne gruppene ved start og etter intervensjonen. Dette gir en dypere innsikt i eventuelle endringer over tid. Når man tester innad i en gruppe over tid undersøker man om det har vært en endring fra pre- til post-test. [@rønnestad] bruker kun uparede t-tester for å vurdere forskjeller mellom gruppene. [@rønnestad2016] bruker en annen tilnærming ved å benytte toveis ANOVA for å vurdere forskjellen mellom gruppene. [@almquist2022] vurderer forskjeller mellom grupper ved å bruke en blandet lineær modell og inkluderer kovariater. Samtlige studier brukte også grafer og deskriptiv statistikk for å vise at treningsbelastningen mellom gruppene og utgangspunktet til forsøkspersonene var likt.

@rønnestad2014, @rønnestad og @rønnestad2019 så en signifikant økning i maksimalt oksygenopptak mellom tradisjonell og bolkperiodisering. Disse studiene fant ingen forskjell på 4mmol·L-1effekt. Det fant derimot Rønnestad (2016). De fant også en signifikant forskjell på maksimal aerob kapasitet (W/kg). (Almquist et al., 2022) fant kun en økning i RBCV (red blood cell volume) i favør blokkperiodisering etter intervensjonen.

Alle studiene utenom [@almquist2022] kunne konkludere med at bolkperiodisering ga større treningsadaptasjoner enn tradisjonell periodisering. [@almquist2022] fant ingen forbedringer på sykkelprestasjon.
