project:
  type: book

book:
  title: "IDR4000_MAPPEEKSAMEN"
  author: "409"
  date: "11.17.2023"
  chapters:
    - index.qmd
    - 01-reliabilitet.qmd
    - 02-labrapport.qmd
    - 03-vitenskapfil.qmd
    - 04-studie_design.qmd
    - 05-repeated_measures.qmd
    - references.bib

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt